# Expondo os mapeamentos dos nodes do pacote BlueeUtils
from .bluee_utils import (
    NODE_CLASS_MAPPINGS as _NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = _NODE_CLASS_MAPPINGS
NODE_DISPLAY_NAME_MAPPINGS = _NODE_DISPLAY_NAME_MAPPINGS


